### ISSUE TITLE
无法正常安装使用

### ISSUE THREAD

**Issue by yfzuix** [ropon/newpanel#5]
已在azure 阿里云轻量 腾讯云轻量 本地虚拟机测试
系统centos7/8 Debian10/11

Centos 安装完成按照提示重启后 ssh无法连接 面板使用`systemctl start newpanel`命令 无法启动和访问
Debian情况基本相同 安装重启后ssh能连接 面板无法启动和访问

安装完成时截图基本跟下图差不多
![](https://s3.bmp.ovh/imgs/2022/07/12/4f700b358939e71a.png)

**Comment by ropon** [comment]
从提示看python3环境安装有问题

**Comment by ropon** [comment]
已修复，python3依赖的问题
